# Generated by Django 3.2.12 on 2022-04-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil_produk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='kreated_at',
            new_name='created_at',
        ),
    ]
