# Generated by Django 4.0.2 on 2022-06-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_time_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time',
        ),
    ]
