# Generated by Django 3.2 on 2022-06-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20220421_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproduk',
            name='gambar',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='reviewproduk',
            name='rating',
            field=models.URLField(),
        ),
    ]
