# Generated by Django 3.2.7 on 2022-04-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.BigIntegerField(default=100000)),
                ('name', models.TextField(default='example : Anugrah Shop')),
                ('email', models.EmailField(default='example : anugrah_shop123@somemailhosting.com', max_length=254)),
                ('address', models.TextField(default='Write your address here...')),
            ],
        ),
    ]
