# Generated by Django 3.2.13 on 2022-04-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapembeli',
            name='kelurahan',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='datapembeli',
            name='kodepos',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='datapembeli',
            name='kota',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='datapembeli',
            name='alamat',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='datapembeli',
            name='nama',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
