# Generated by Django 3.2 on 2022-06-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukti', '0002_auto_20220422_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapembeli',
            name='alamat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datapembeli',
            name='kelurahan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datapembeli',
            name='kodepos',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datapembeli',
            name='kota',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datapembeli',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
