# Generated by Django 3.2 on 2022-06-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bukti', '0003_auto_20220612_1532'),
        ('bukti', '0003_auto_20220613_1039'),
    ]

    operations = [
    ]
